const robots = [
  {
    id: 1,
    name: "test",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test1",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test2",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test3",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
  {
    id: 1,
    name: "test4",
    username: "test1",
    email: "test1@gmail.com",
  },
];
export default robots;
